server:
  port: 8081

spring:
  application:
    name: customer-service

eureka:
  client:
    service-url:
      defaultZone: http://175.24.183.52:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}

feign:
  circuitbreaker:
    enabled: true
