server:
  port: 8081
spring:
  application:
    name: nacos-client-b
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        group: A_GROUP # 组名
        service: user-service # 真正的服务名称
        namespace: ae05e655-a027-4873-a96b-dd7b1dcdf9f1
